export { default as NavBar } from './NavBar'
export { default as Filters } from './Filters'
export { default as Categories } from './Categories'
export { default as Popular } from './Popular'
export { default as Veggies } from './Veggies'
